id: AD7C949A5
title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness the Dalai
  Lama'
type: translation
pechas:
- IAA882123
- I9EB7BFEB
- I293026B3
- IBC638599
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:49.841558
  last_modified_at: 2023-01-04 11:53:49.841562
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  IAA882123/779A: 9A80
  I9EB7BFEB/527D: 9A80
  I293026B3/E0DF: 9A80
  IBC638599/FC2A: 9A80
